#pragma once
#include <Windows.h>

enum Color
{
    Black = 0,
    Blue = FOREGROUND_BLUE,
    Green = FOREGROUND_GREEN,
    Cyan = FOREGROUND_GREEN | FOREGROUND_BLUE,
    Red = FOREGROUND_RED,
    Magenta = FOREGROUND_RED | FOREGROUND_BLUE,
    Yellow = FOREGROUND_RED | FOREGROUND_GREEN,
    White = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    Gray = FOREGROUND_INTENSITY,
    BrightBlue = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightGreen = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    BrightCyan = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightRed = FOREGROUND_RED | FOREGROUND_INTENSITY,
    BrightMagenta = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    BrightYellow = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    BrightWhite = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,

    BackgroundGreen = BACKGROUND_GREEN,
    BackgroundRed = BACKGROUND_RED,
    BackgroundGrey = BACKGROUND_INTENSITY,
    BackgroundYellow = BACKGROUND_RED | BACKGROUND_GREEN,
};